"""
Comprehensive tests for AI-generated image detection.

Tests cover:
- Metadata-based detection (DALL-E, Midjourney, Stable Diffusion)
- C2PA chunk detection (PNG and JPEG)
- Statistical analysis
- Confidence scoring and thresholds
- Integration with worker
- Edge cases and various image formats
- Return types and validation
"""

import pytest
from PIL import Image
from PIL.PngImagePlugin import PngInfo
import numpy as np
import struct
from io import BytesIO
from image_worker.ai_generated_detector import AIGeneratedDetector


# ============================================================================
# FIXTURES
# ============================================================================


@pytest.fixture
def detector():
    """Create AI detector instance."""
    return AIGeneratedDetector()


@pytest.fixture
def dalle_image():
    """Create image with DALL-E metadata."""
    img = Image.new("RGB", (512, 512), color=(100, 150, 200))
    metadata = PngInfo()
    metadata.add_text("Software", "DALL-E by OpenAI")

    buffer = BytesIO()
    img.save(buffer, format="PNG", pnginfo=metadata)
    buffer.seek(0)
    return Image.open(buffer)


@pytest.fixture
def midjourney_image():
    """Create image with Midjourney metadata."""
    img = Image.new("RGB", (512, 512), color=(200, 100, 150))
    metadata = PngInfo()
    metadata.add_text("Artist", "Generated by Midjourney")

    buffer = BytesIO()
    img.save(buffer, format="PNG", pnginfo=metadata)
    buffer.seek(0)
    return Image.open(buffer)


@pytest.fixture
def stable_diffusion_image():
    """Create image with Stable Diffusion metadata."""
    img = Image.new("RGB", (512, 512), color=(150, 200, 100))
    metadata = PngInfo()
    metadata.add_text("CreatorTool", "Stable Diffusion")

    buffer = BytesIO()
    img.save(buffer, format="PNG", pnginfo=metadata)
    buffer.seek(0)
    return Image.open(buffer)


@pytest.fixture
def real_photo():
    """Create realistic photo with camera metadata."""
    np.random.seed(42)
    base = np.ones((512, 512, 3), dtype=np.uint8) * 128
    noise = np.random.normal(0, 15, base.shape).astype(np.int16)
    noisy_img = np.clip(base + noise, 0, 255).astype(np.uint8)

    img = Image.fromarray(noisy_img, "RGB")
    metadata = PngInfo()
    metadata.add_text("Software", "Canon EOS 5D Mark IV")
    metadata.add_text("Make", "Canon")
    metadata.add_text("Model", "Canon EOS 5D Mark IV")

    buffer = BytesIO()
    img.save(buffer, format="PNG", pnginfo=metadata)
    buffer.seek(0)
    return Image.open(buffer)


@pytest.fixture
def synthetic_image():
    """Create very smooth synthetic image."""
    img_array = np.zeros((512, 512, 3), dtype=np.uint8)
    for i in range(512):
        img_array[i, :, 0] = int(255 * i / 512)
        img_array[i, :, 1] = int(255 * (512 - i) / 512)
        img_array[i, :, 2] = 128

    return Image.fromarray(img_array, "RGB")


# ============================================================================
# METADATA DETECTION TESTS
# ============================================================================


class TestMetadataDetection:
    """Test metadata-based AI detection."""

    def test_dalle_detection(self, detector, dalle_image):
        """Test DALL-E image is detected."""
        is_ai, source, confidence = detector.check_ai_generated(dalle_image)

        assert is_ai is True
        assert confidence >= 0.90
        assert "DALL-E" in source or "Metadata" in source

    def test_midjourney_detection(self, detector, midjourney_image):
        """Test Midjourney image is detected."""
        is_ai, source, confidence = detector.check_ai_generated(midjourney_image)

        assert is_ai is True
        assert confidence >= 0.90
        assert "Midjourney" in source or "Metadata" in source

    def test_stable_diffusion_detection(self, detector, stable_diffusion_image):
        """Test Stable Diffusion image is detected."""
        is_ai, source, confidence = detector.check_ai_generated(stable_diffusion_image)

        assert is_ai is True
        assert confidence >= 0.90
        assert "Stable Diffusion" in source or "Metadata" in source

    def test_real_photo_not_detected(self, detector, real_photo):
        """Test real photo is not flagged as AI."""
        is_ai, source, confidence = detector.check_ai_generated(real_photo)

        # Should either not detect or have low confidence
        if is_ai:
            assert confidence < 0.70

    @pytest.mark.parametrize(
        "platform_text,expected_detected",
        [
            ("DALL-E by OpenAI", True),
            ("Generated by Midjourney", True),
            ("Stable Diffusion", True),
            ("Adobe Photoshop", False),  # Editing software, not AI
            ("GIMP", False),  # Editing software
            ("Canon Camera", False),  # Camera
        ],
    )
    def test_metadata_platform_detection(
        self, detector, platform_text, expected_detected
    ):
        """Test detection of various platform metadata."""
        img = Image.new("RGB", (512, 512), color=(128, 128, 128))
        metadata = PngInfo()
        metadata.add_text("Software", platform_text)

        buffer = BytesIO()
        img.save(buffer, format="PNG", pnginfo=metadata)
        buffer.seek(0)
        test_img = Image.open(buffer)

        is_ai, source, confidence = detector.check_ai_generated(test_img)

        # Note: Actual detection depends on detector implementation
        if expected_detected:
            assert is_ai is True or confidence > 0.0
        assert isinstance(is_ai, bool)


# ============================================================================
# STATISTICAL ANALYSIS TESTS
# ============================================================================


class TestStatisticalAnalysis:
    """Test statistical analysis features."""

    def test_synthetic_image_analysis(self, detector, synthetic_image):
        """Test statistical analysis on synthetic image."""
        is_ai, source, confidence = detector.check_ai_generated(synthetic_image)

        # Result depends on implementation thresholds
        assert isinstance(is_ai, bool)
        assert 0.0 <= confidence <= 1.0
        assert isinstance(source, str)

    def test_image_without_metadata(self, detector):
        """Test image without any metadata."""
        img = Image.new("RGB", (512, 512), color=(128, 128, 128))

        is_ai, source, confidence = detector.check_ai_generated(img)

        # Should use statistical analysis
        assert isinstance(is_ai, bool)
        assert 0.0 <= confidence <= 1.0


# ============================================================================
# CONFIDENCE SCORING TESTS
# ============================================================================


class TestConfidenceScoring:
    """Test confidence scoring and thresholds."""

    def test_confidence_range(self, detector, dalle_image):
        """Test that confidence is between 0 and 1."""
        is_ai, source, confidence = detector.check_ai_generated(dalle_image)

        assert 0.0 <= confidence <= 1.0
        assert isinstance(confidence, (float, int))

    def test_high_confidence_metadata(self, detector, dalle_image):
        """Test that metadata detection has high confidence."""
        is_ai, source, confidence = detector.check_ai_generated(dalle_image)

        if is_ai:
            assert confidence >= 0.90

    @pytest.mark.parametrize(
        "threshold",
        [0.50, 0.60, 0.70, 0.80, 0.90, 0.95],
    )
    def test_confidence_thresholds(self, detector, dalle_image, threshold):
        """Test behavior at different confidence thresholds."""
        is_ai, source, confidence = detector.check_ai_generated(dalle_image)

        would_trigger = is_ai and confidence >= threshold

        # DALL-E should trigger at all tested thresholds
        if threshold <= 0.90:
            assert would_trigger

    def test_threshold_based_short_circuit(self, detector, dalle_image):
        """Test that high-confidence detections can short-circuit plagiarism checks."""
        is_ai, source, confidence = detector.check_ai_generated(dalle_image)

        # Simulate worker logic: threshold of 0.70 for short-circuit
        if is_ai and confidence >= 0.70:
            # This would short-circuit plagiarism detection
            should_short_circuit = True
        else:
            should_short_circuit = False

        # DALL-E with metadata should trigger short-circuit
        assert should_short_circuit is True


# ============================================================================
# EDGE CASES AND IMAGE FORMAT TESTS
# ============================================================================


class TestEdgeCases:
    """Test edge cases and error handling."""

    def test_small_image(self, detector):
        """Test with very small image."""
        img = Image.new("RGB", (10, 10), color=(128, 128, 128))

        is_ai, source, confidence = detector.check_ai_generated(img)

        # Should handle gracefully
        assert isinstance(is_ai, bool)
        assert isinstance(confidence, (float, int))

    def test_large_image(self, detector):
        """Test with large image."""
        img = Image.new("RGB", (4096, 4096), color=(128, 128, 128))

        is_ai, source, confidence = detector.check_ai_generated(img)

        # Should handle gracefully
        assert isinstance(is_ai, bool)
        assert isinstance(confidence, (float, int))

    def test_grayscale_image(self, detector):
        """Test with grayscale image."""
        img = Image.new("L", (512, 512), color=128)

        is_ai, source, confidence = detector.check_ai_generated(img)

        assert isinstance(is_ai, bool)
        assert isinstance(confidence, (float, int))

    def test_rgba_image(self, detector):
        """Test with RGBA image (with alpha)."""
        img = Image.new("RGBA", (512, 512), color=(128, 128, 128, 255))

        is_ai, source, confidence = detector.check_ai_generated(img)

        assert isinstance(is_ai, bool)
        assert isinstance(confidence, (float, int))

    def test_image_with_exif(self, detector):
        """Test image with EXIF metadata."""
        img = Image.new("RGB", (512, 512), color=(128, 128, 128))

        # Note: PIL doesn't easily support EXIF writing for test images
        # This tests that the detector doesn't crash
        is_ai, source, confidence = detector.check_ai_generated(img)

        assert isinstance(is_ai, bool)

    @pytest.mark.parametrize(
        "color",
        [
            (255, 0, 0),  # Red
            (0, 255, 0),  # Green
            (0, 0, 255),  # Blue
            (255, 255, 255),  # White
            (0, 0, 0),  # Black
            (128, 128, 128),  # Gray
        ],
    )
    def test_various_solid_colors(self, detector, color):
        """Test with various solid color images."""
        img = Image.new("RGB", (512, 512), color=color)

        is_ai, source, confidence = detector.check_ai_generated(img)

        # Should handle all colors
        assert isinstance(is_ai, bool)
        assert 0.0 <= confidence <= 1.0


# ============================================================================
# RETURN TYPE VALIDATION TESTS
# ============================================================================


class TestReturnTypes:
    """Test that return types are correct."""

    def test_return_tuple_length(self, detector, dalle_image):
        """Test that function returns 3-element tuple."""
        result = detector.check_ai_generated(dalle_image)

        assert isinstance(result, tuple)
        assert len(result) == 3

    def test_return_types(self, detector, dalle_image):
        """Test that return types are correct."""
        is_ai, source, confidence = detector.check_ai_generated(dalle_image)

        assert isinstance(is_ai, bool)
        assert isinstance(source, str)
        assert isinstance(confidence, (float, int))

    def test_source_non_empty(self, detector, dalle_image):
        """Test that source string is non-empty."""
        is_ai, source, confidence = detector.check_ai_generated(dalle_image)

        assert len(source) > 0


# ============================================================================
# INTEGRATION AND CONSISTENCY TESTS
# ============================================================================


class TestIntegration:
    """Integration tests for AI detector."""

    def test_multiple_detections_consistent(self, detector, dalle_image):
        """Test that multiple detections are consistent."""
        result1 = detector.check_ai_generated(dalle_image)
        result2 = detector.check_ai_generated(dalle_image)

        assert result1[0] == result2[0]  # is_ai
        assert result1[1] == result2[1]  # source
        assert result1[2] == result2[2]  # confidence

    def test_different_platforms_detected_differently(
        self, detector, dalle_image, midjourney_image
    ):
        """Test that different platforms are identified."""
        dalle_result = detector.check_ai_generated(dalle_image)
        mj_result = detector.check_ai_generated(midjourney_image)

        # Both should be detected as AI
        assert dalle_result[0] is True
        assert mj_result[0] is True

        # Sources might be different
        assert isinstance(dalle_result[1], str)
        assert isinstance(mj_result[1], str)

    def test_real_vs_ai_distinction(self, detector, dalle_image, real_photo):
        """Test that detector distinguishes between real and AI images."""
        ai_result = detector.check_ai_generated(dalle_image)
        real_result = detector.check_ai_generated(real_photo)

        # AI image should be detected
        assert ai_result[0] is True
        assert ai_result[2] >= 0.90

        # Real photo should either not be detected or have low confidence
        if real_result[0]:
            assert real_result[2] < 0.70


# ============================================================================
# C2PA CHUNK DETECTION TESTS
# ============================================================================


class TestC2PAChunkDetection:
    """Test C2PA chunk detection for AI-generated images."""

    @pytest.fixture
    def detector(self):
        """Create AI detector instance."""
        return AIGeneratedDetector()

    def create_png_with_chunk(self, chunk_type, chunk_data):
        """Helper to create PNG with custom chunk."""
        img = Image.new("RGB", (256, 256), color=(128, 128, 128))
        buffer = BytesIO()
        img.save(buffer, format="PNG")

        png_data = bytearray(buffer.getvalue())

        iend_pos = png_data.rfind(b"IEND")
        if iend_pos == -1:
            return BytesIO(bytes(png_data))

        iend_start = iend_pos - 4

        chunk_length = len(chunk_data)
        chunk = struct.pack(">I", chunk_length)
        chunk += chunk_type.encode("latin1")
        chunk += chunk_data

        crc = 0xFFFFFFFF
        for byte in chunk_type.encode("latin1") + chunk_data:
            crc ^= byte
            for _ in range(8):
                if crc & 1:
                    crc = (crc >> 1) ^ 0xEDB88320
                else:
                    crc >>= 1
        crc ^= 0xFFFFFFFF
        chunk += struct.pack(">I", crc)

        new_png = png_data[:iend_start] + chunk + png_data[iend_start:]

        return BytesIO(bytes(new_png))

    def test_c2pa_chunk_cabx_openai(self, detector):
        """Test detection of caBX chunk with OpenAI metadata."""
        chunk_data = b"openai:dalle-3:generated"
        buffer = self.create_png_with_chunk("caBX", chunk_data)

        img = Image.open(buffer)
        is_ai, source, confidence = detector.check_ai_generated(img)

        assert is_ai is True
        assert confidence >= 0.95
        assert "C2PA" in source or "OpenAI" in source.lower()

    def test_c2pa_chunk_c2pa(self, detector):
        """Test detection of c2pa chunk."""
        chunk_data = b"adobe:firefly:metadata"
        buffer = self.create_png_with_chunk("c2pa", chunk_data)

        img = Image.open(buffer)
        is_ai, source, confidence = detector.check_ai_generated(img)

        assert is_ai is True
        assert confidence >= 0.95

    def test_c2pa_chunk_c2ma(self, detector):
        """Test detection of c2ma chunk."""
        chunk_data = b"midjourney:v6:manifest"
        buffer = self.create_png_with_chunk("c2ma", chunk_data)

        img = Image.open(buffer)
        is_ai, source, confidence = detector.check_ai_generated(img)

        assert is_ai is True
        assert confidence >= 0.95

    def test_c2pa_chunk_c2as(self, detector):
        """Test detection of c2as chunk."""
        chunk_data = b"stability:sdxl:assertion"
        buffer = self.create_png_with_chunk("c2as", chunk_data)

        img = Image.open(buffer)
        is_ai, source, confidence = detector.check_ai_generated(img)

        assert is_ai is True
        assert confidence >= 0.95

    def test_no_c2pa_chunks(self, detector):
        """Test image without C2PA chunks."""
        img = Image.new("RGB", (256, 256), color=(128, 128, 128))
        buffer = BytesIO()
        img.save(buffer, format="PNG")
        buffer.seek(0)

        img = Image.open(buffer)
        is_ai, source, confidence = detector.check_ai_generated(img)

        assert isinstance(is_ai, bool)
        assert 0.0 <= confidence <= 1.0

    def test_c2pa_chunk_with_generator_chatgpt(self, detector):
        """Test C2PA chunk with ChatGPT generator."""
        chunk_data = b'{"generator": "chatgpt-dalle"}'
        buffer = self.create_png_with_chunk("caBX", chunk_data)

        img = Image.open(buffer)
        is_ai, source, confidence = detector.check_ai_generated(img)

        assert is_ai is True
        assert confidence >= 0.98

    def test_c2pa_chunk_with_generator_adobe(self, detector):
        """Test C2PA chunk with Adobe generator."""
        chunk_data = b'{"generator": "Adobe Firefly"}'
        buffer = self.create_png_with_chunk("caBX", chunk_data)

        img = Image.open(buffer)
        is_ai, source, confidence = detector.check_ai_generated(img)

        assert is_ai is True
        assert confidence >= 0.98

    def test_c2pa_chunk_with_generator_midjourney(self, detector):
        """Test C2PA chunk with Midjourney generator."""
        chunk_data = b"midjourney-v6-alpha"
        buffer = self.create_png_with_chunk("c2pa", chunk_data)

        img = Image.open(buffer)
        is_ai, source, confidence = detector.check_ai_generated(img)

        assert is_ai is True
        assert confidence >= 0.98

    def test_c2pa_chunk_with_generator_stability(self, detector):
        """Test C2PA chunk with Stability AI generator."""
        chunk_data = b"stability.ai/sdxl-turbo"
        buffer = self.create_png_with_chunk("c2ma", chunk_data)

        img = Image.open(buffer)
        is_ai, source, confidence = detector.check_ai_generated(img)

        assert is_ai is True
        assert confidence >= 0.98


# ============================================================================
# JPEG C2PA DETECTION TESTS
# ============================================================================


class TestJPEGC2PADetection:
    """Test C2PA detection in JPEG images."""

    @pytest.fixture
    def detector(self):
        """Create AI detector instance."""
        return AIGeneratedDetector()

    def test_jpeg_with_app1_segment(self, detector):
        """Test JPEG with APP1 segment containing C2PA."""
        img = Image.new("RGB", (256, 256), color=(128, 128, 128))
        buffer = BytesIO()
        img.save(buffer, format="JPEG", quality=95)

        jpeg_data = bytearray(buffer.getvalue())

        if jpeg_data[0:2] != b"\xff\xd8":
            pytest.skip("Not a valid JPEG")

        c2pa_data = b"c2pa:adobe:firefly"
        app1_segment = b"\xff\xe1"
        app1_segment += struct.pack(">H", len(c2pa_data) + 2)
        app1_segment += c2pa_data

        new_jpeg = jpeg_data[0:2] + app1_segment + jpeg_data[2:]

        buffer = BytesIO(bytes(new_jpeg))
        img = Image.open(buffer)

        is_ai, source, confidence = detector.check_ai_generated(img)

        assert is_ai is True
        assert confidence >= 0.95

    def test_jpeg_without_c2pa(self, detector):
        """Test JPEG without C2PA metadata."""
        img = Image.new("RGB", (256, 256), color=(128, 128, 128))
        buffer = BytesIO()
        img.save(buffer, format="JPEG", quality=95)
        buffer.seek(0)

        img = Image.open(buffer)
        is_ai, source, confidence = detector.check_ai_generated(img)

        assert isinstance(is_ai, bool)
        assert 0.0 <= confidence <= 1.0


# ============================================================================
# EXTENDED EDGE CASES
# ============================================================================


class TestEdgeCasesExtended:
    """Extended edge case testing."""

    @pytest.fixture
    def detector(self):
        """Create AI detector instance."""
        return AIGeneratedDetector()

    def test_corrupted_png_chunks(self, detector):
        """Test handling of corrupted PNG chunks."""
        img = Image.new("RGB", (256, 256), color=(128, 128, 128))
        buffer = BytesIO()
        img.save(buffer, format="PNG")

        png_data = bytearray(buffer.getvalue())
        if len(png_data) > 100:
            png_data[50:60] = b"\x00" * 10

        try:
            buffer = BytesIO(bytes(png_data))
            img = Image.open(buffer)
            is_ai, source, confidence = detector.check_ai_generated(img)

            assert isinstance(is_ai, bool)
            assert 0.0 <= confidence <= 1.0
        except Exception:
            pass

    def test_very_high_saturation_image(self, detector):
        """Test with very high saturation image."""
        img_array = np.zeros((256, 256, 3), dtype=np.uint8)
        img_array[:, :, 0] = 255
        img_array[:, :, 1] = 0
        img_array[:, :, 2] = 255
        img = Image.fromarray(img_array, "RGB")

        is_ai, source, confidence = detector.check_ai_generated(img)

        assert isinstance(is_ai, bool)
        assert 0.0 <= confidence <= 1.0

    def test_checkerboard_pattern(self, detector):
        """Test with checkerboard pattern."""
        img_array = np.zeros((256, 256, 3), dtype=np.uint8)
        for i in range(256):
            for j in range(256):
                if (i // 16 + j // 16) % 2 == 0:
                    img_array[i, j] = [255, 255, 255]
        img = Image.fromarray(img_array, "RGB")

        is_ai, source, confidence = detector.check_ai_generated(img)

        assert isinstance(is_ai, bool)
        assert 0.0 <= confidence <= 1.0


# ============================================================================
# DETECTION STATS TESTS
# ============================================================================


class TestGetDetectionStats:
    """Test get_detection_stats method."""

    @pytest.fixture
    def detector(self):
        """Create AI detector instance."""
        return AIGeneratedDetector()

    def test_get_detection_stats_returns_dict(self, detector):
        """Test that get_detection_stats returns a dictionary."""
        stats = detector.get_detection_stats()

        assert isinstance(stats, dict)

    def test_get_detection_stats_has_keys(self, detector):
        """Test that stats dict has expected keys."""
        detector.check_ai_generated(Image.new("RGB", (256, 256), color=(128, 128, 128)))

        stats = detector.get_detection_stats()

        assert isinstance(stats, dict)
        expected_keys = ["total_checked", "ai_detected", "detection_rate"]
        for key in expected_keys:
            if key in stats:
                assert isinstance(stats[key], (int, float))

    def test_get_detection_stats_increments(self, detector):
        """Test that stats increment correctly."""
        initial_stats = detector.get_detection_stats()

        detector.check_ai_generated(Image.new("RGB", (256, 256), color=(128, 128, 128)))
        detector.check_ai_generated(Image.new("RGB", (256, 256), color=(200, 100, 50)))

        updated_stats = detector.get_detection_stats()

        if "total_checked" in updated_stats and "total_checked" in initial_stats:
            assert updated_stats["total_checked"] >= initial_stats["total_checked"]


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
