"""
AI-Generated Image Detection Module

Detects if an image was generated by AI models (DALL-E, Midjourney, Stable Diffusion, etc.)
using multiple detection strategies including statistical analysis and ML-based classifiers.
"""

import logging
import numpy as np
from typing import Tuple, Optional, Dict, Any
from PIL import Image

logger = logging.getLogger(__name__)


class AIGeneratedDetector:
    """
    Detect AI-generated images using multiple strategies.

    Detection methods:
    1. Statistical analysis (frequency domain artifacts)
    2. Noise pattern analysis (GAN fingerprints)
    3. Metadata inspection (generation software markers)
    4. External API services (if available)
    """

    def __init__(self):
        """Initialize AI-generated image detector."""
        # Known AI generation platforms
        self.ai_platforms = [
            "DALL-E",
            "DALL·E",
            "OpenAI",
            "Midjourney",
            "MidJourney",
            "Stable Diffusion",
            "StabilityAI",
            "Adobe Firefly",
            "Firefly",
            "Imagen",
            "Google Imagen",
            "Leonardo.ai",
            "Leonardo",
            "Playground AI",
            "DreamStudio",
            "Craiyon",
            "NightCafe",
        ]

        logger.info("AIGeneratedDetector initialized")

    def _check_c2pa_chunks(
        self, image: Image.Image
    ) -> Tuple[bool, Optional[str], float]:
        """
        Check for C2PA (Content Authenticity) metadata in PNG/JPEG files.

        C2PA is used by OpenAI (DALL-E), Adobe (Firefly), and other AI generators
        to embed content provenance information.

        Returns:
            Tuple of (is_ai, source, confidence)
        """
        try:
            import struct
            from io import BytesIO

            # Get the raw image data
            if hasattr(image, "fp") and image.fp:
                # If image was opened from file, get raw data
                image.fp.seek(0)
                data = image.fp.read()
            else:
                # Convert image to bytes
                buffer = BytesIO()
                image.save(buffer, format=image.format or "PNG")
                data = buffer.getvalue()

            # Check PNG chunks for C2PA
            if image.format == "PNG":
                if data[:8] != b"\x89PNG\r\n\x1a\n":
                    return False, None, 0.0

                pos = 8
                while pos < len(data) - 12:
                    try:
                        length = struct.unpack(">I", data[pos : pos + 4])[0]
                        chunk_type = data[pos + 4 : pos + 8].decode(
                            "latin-1", errors="ignore"
                        )

                        # Check for C2PA chunks
                        # caBX = C2PA Content Authenticity Box
                        # c2pa = C2PA manifest
                        # c2ma = C2PA manifest store
                        # c2as = C2PA assertions
                        if chunk_type in ["caBX", "c2pa", "c2ma", "c2as"]:
                            chunk_data = data[pos + 8 : pos + 8 + min(length, 1000)]

                            # Look for C2PA identifiers in the chunk
                            chunk_str = chunk_data.decode(
                                "latin-1", errors="ignore"
                            ).lower()

                            # Check for known AI generator identifiers in C2PA data
                            ai_generators = {
                                "openai": ("OpenAI (DALL-E)", 0.99),
                                "dall-e": ("OpenAI (DALL-E)", 0.99),
                                "dalle": ("OpenAI (DALL-E)", 0.99),
                                "chatgpt": ("OpenAI (ChatGPT)", 0.99),
                                "adobe": ("Adobe Firefly", 0.98),
                                "firefly": ("Adobe Firefly", 0.98),
                                "midjourney": ("Midjourney", 0.98),
                                "stability": ("Stable Diffusion", 0.98),
                                "stable diffusion": ("Stable Diffusion", 0.98),
                            }

                            for keyword, (source, confidence) in ai_generators.items():
                                if keyword in chunk_str:
                                    logger.info(
                                        f"C2PA metadata found: {source} in {chunk_type} chunk"
                                    )
                                    return True, f"C2PA: {source}", confidence

                            # If we found a C2PA chunk but no specific generator, still flag it
                            # as very likely AI-generated
                            logger.info(
                                f"C2PA chunk ({chunk_type}) found - likely AI-generated"
                            )
                            return True, f"C2PA: Unknown AI generator", 0.95

                        pos += 12 + length

                    except (struct.error, UnicodeDecodeError, IndexError):
                        break

            # Check JPEG for C2PA in APP segments
            elif image.format in ["JPEG", "JPG"]:
                pos = 0
                if data[:2] != b"\xff\xd8":  # JPEG SOI marker
                    return False, None, 0.0

                pos = 2
                while pos < len(data) - 4:
                    try:
                        if data[pos] != 0xFF:
                            break

                        marker = data[pos + 1]
                        # Skip markers without length
                        if marker in [
                            0xD0,
                            0xD1,
                            0xD2,
                            0xD3,
                            0xD4,
                            0xD5,
                            0xD6,
                            0xD7,
                            0xD8,
                            0xD9,
                        ]:
                            pos += 2
                            continue

                        if pos + 4 > len(data):
                            break

                        length = struct.unpack(">H", data[pos + 2 : pos + 4])[0]
                        segment_data = data[pos + 4 : pos + 2 + min(length, 1000)]

                        # Check APP11 (C2PA marker) and other APP segments
                        if marker in range(0xE0, 0xF0):  # APP0-APP15
                            segment_str = segment_data.decode(
                                "latin-1", errors="ignore"
                            ).lower()

                            if "c2pa" in segment_str or "jumbf" in segment_str:
                                logger.info(
                                    f"C2PA data found in JPEG APP{marker - 0xE0} segment"
                                )
                                return True, "C2PA: AI-generated (JPEG)", 0.95

                        pos += 2 + length

                    except (struct.error, UnicodeDecodeError, IndexError):
                        break

            return False, None, 0.0

        except Exception as e:
            logger.debug(f"C2PA chunk check failed: {e}")
            return False, None, 0.0

    def check_ai_generated(
        self, image: Image.Image
    ) -> Tuple[bool, Optional[str], float]:
        """
        Check if image was AI-generated.

        Args:
            image: PIL Image object

        Returns:
            Tuple of (is_ai_generated, source/method, confidence)
            - is_ai_generated: True if detected as AI-generated
            - source: AI platform or detection method
            - confidence: Confidence score 0.0-1.0
        """
        try:
            # Strategy 1: Check metadata for AI generation markers
            metadata_result = self._check_metadata_for_ai(image)
            if metadata_result[0] and metadata_result[2] > 0.90:
                logger.info(f"AI-generated detected via metadata: {metadata_result[1]}")
                return metadata_result

            # Strategy 2: Statistical analysis for GAN/diffusion artifacts
            statistical_result = self._statistical_analysis(image)
            if statistical_result[0] and statistical_result[2] > 0.65:
                logger.info(
                    f"AI-generated detected via statistics: {statistical_result[1]}"
                )
                return statistical_result

            # Strategy 3: Noise pattern analysis
            noise_result = self._analyze_noise_patterns(image)
            if noise_result[0] and noise_result[2] > 0.65:
                logger.info(
                    f"AI-generated detected via noise analysis: {noise_result[1]}"
                )
                return noise_result

            # Combine all scores with weighted average
            # Metadata is most reliable, followed by statistical, then noise
            weights = [0.5, 0.35, 0.15]  # metadata, statistical, noise
            scores = [metadata_result[2], statistical_result[2], noise_result[2]]
            weighted_confidence = sum(w * s for w, s in zip(weights, scores))

            # Also consider max score (any single strong indicator)
            max_confidence = max(scores)

            # Use the higher of weighted average or max score
            combined_confidence = max(weighted_confidence, max_confidence)

            # Lower threshold for combined indicators
            if combined_confidence > 0.50:
                # Determine which method contributed most
                if metadata_result[2] > 0.3:
                    source = f"Multiple indicators (metadata partial)"
                elif statistical_result[2] > 0.3:
                    source = f"Multiple indicators (statistical)"
                elif noise_result[2] > 0.3:
                    source = f"Multiple indicators (noise)"
                else:
                    source = "Multiple indicators"

                logger.info(
                    f"AI-generated detected via combined analysis: {source}, confidence={combined_confidence:.2f}"
                )
                return True, source, combined_confidence

            logger.info(
                f"No AI generation indicators found (max confidence: {max_confidence:.2f})"
            )
            return False, None, combined_confidence

        except Exception as e:
            logger.error(f"Error in AI generation detection: {e}")
            return False, None, 0.0

    def _check_metadata_for_ai(
        self, image: Image.Image
    ) -> Tuple[bool, Optional[str], float]:
        """
        Check EXIF and metadata for AI generation indicators.

        Returns:
            Tuple of (is_ai, source, confidence)
        """
        try:
            # Check for C2PA metadata in PNG chunks (OpenAI, Adobe, etc.)
            c2pa_result = self._check_c2pa_chunks(image)
            if c2pa_result[0]:
                return c2pa_result

            # Extract EXIF data
            exif_data = image.getexif()

            if exif_data:
                # EXIF tag IDs for fields to check
                fields_to_check = {
                    305: "Software",  # Software
                    11: "ProcessingSoftware",  # ProcessingSoftware
                    315: "Artist",  # Artist
                    33432: "Copyright",  # Copyright
                    271: "Make",  # Make
                    272: "Model",  # Model
                    270: "ImageDescription",  # ImageDescription
                    37510: "UserComment",  # UserComment (may be bytes)
                }

                for tag_id, field_name in fields_to_check.items():
                    value = exif_data.get(tag_id)
                    if value:
                        # Handle bytes values (common for UserComment)
                        if isinstance(value, bytes):
                            try:
                                value_str = value.decode("utf-8", errors="ignore")
                            except (UnicodeDecodeError, AttributeError):
                                continue
                        elif isinstance(value, str):
                            value_str = value
                        else:
                            value_str = str(value)

                        # Check against known AI platforms
                        for platform in self.ai_platforms:
                            if platform.lower() in value_str.lower():
                                logger.info(
                                    f"AI platform detected in EXIF {field_name}: {platform}"
                                )
                                return True, f"Metadata: {platform}", 0.98

                        # Check for generic AI indicators
                        ai_keywords = [
                            "ai generated",
                            "ai-generated",
                            "artificial intelligence",
                            "neural network",
                            "diffusion",
                            "gan",
                            "generative",
                        ]
                        for keyword in ai_keywords:
                            if keyword in value_str.lower():
                                logger.info(
                                    f"AI keyword detected in EXIF {field_name}: {keyword}"
                                )
                                return True, f"Metadata: {keyword}", 0.95

            # Check image info dictionary (PNG tEXt chunks, etc.)
            if hasattr(image, "info") and image.info:
                info = image.info
                for key, value in info.items():
                    if isinstance(value, str):
                        # Check for AI platforms
                        for platform in self.ai_platforms:
                            if platform.lower() in value.lower():
                                logger.info(
                                    f"AI platform detected in image info[{key}]: {platform}"
                                )
                                return True, f"Image info: {platform}", 0.95

                        # Check for AI keywords
                        ai_keywords = [
                            "ai generated",
                            "ai-generated",
                            "artificial intelligence",
                            "neural network",
                            "diffusion",
                            "gan",
                            "generative",
                            "prompt",
                            "seed",
                            "steps",
                            "sampler",
                        ]
                        for keyword in ai_keywords:
                            if keyword in value.lower():
                                logger.info(
                                    f"AI keyword detected in image info[{key}]: {keyword}"
                                )
                                return True, f"Image info: {keyword}", 0.90

            return False, None, 0.0

        except Exception as e:
            logger.debug(f"Metadata check failed: {e}")
            return False, None, 0.0

    def _statistical_analysis(
        self, image: Image.Image
    ) -> Tuple[bool, Optional[str], float]:
        """
        Analyze statistical properties for AI generation artifacts.

        GAN-generated images often have specific frequency domain characteristics.
        Works on a resized copy to ensure fast processing without losing metadata.

        Returns:
            Tuple of (is_ai, method, confidence)
        """
        try:
            # Create a resized copy for fast processing (preserves original image with metadata)
            # This dramatically speeds up FFT and scipy operations (90s -> <1s)
            width, height = image.size
            max_dim = 512
            if width > max_dim or height > max_dim:
                scale = min(max_dim / width, max_dim / height)
                new_width = int(width * scale)
                new_height = int(height * scale)
                resized_image = image.resize(
                    (new_width, new_height), Image.Resampling.LANCZOS
                )
            else:
                resized_image = image

            # Convert to numpy array
            img_array = np.array(resized_image.convert("RGB"))

            # Analyze frequency domain (FFT)
            confidence_score = 0.0
            indicators = []

            # Check each color channel
            for channel in range(3):
                channel_data = img_array[:, :, channel].astype(float)

                # Compute 2D FFT
                fft = np.fft.fft2(channel_data)
                fft_shift = np.fft.fftshift(fft)
                magnitude_spectrum = np.abs(fft_shift)

                # AI-generated images often have unusual frequency distributions
                # Check for specific patterns

                # 1. Check for high-frequency anomalies (common in GAN outputs)
                height, width = magnitude_spectrum.shape
                center_y, center_x = height // 2, width // 2

                # Sample high-frequency region
                high_freq_region = magnitude_spectrum[
                    0 : center_y // 2, 0 : center_x // 2
                ]
                high_freq_mean = np.mean(high_freq_region)

                # Sample mid-frequency region
                mid_freq_y_start = center_y // 4
                mid_freq_y_end = 3 * center_y // 4
                mid_freq_x_start = center_x // 4
                mid_freq_x_end = 3 * center_x // 4
                mid_freq_region = magnitude_spectrum[
                    mid_freq_y_start:mid_freq_y_end, mid_freq_x_start:mid_freq_x_end
                ]
                mid_freq_mean = np.mean(mid_freq_region)

                # Unusual ratio suggests AI generation
                if mid_freq_mean > 0:
                    freq_ratio = high_freq_mean / mid_freq_mean
                    if freq_ratio > 0.8 or freq_ratio < 0.01:
                        confidence_score += 0.15
                        indicators.append("frequency_anomaly")

            # 2. Check for unnatural smoothness (common in diffusion models)
            grayscale = np.array(resized_image.convert("L"))
            smoothness = self._calculate_smoothness(grayscale)

            if smoothness > 0.85:  # Too smooth for natural photo
                confidence_score += 0.25
                indicators.append("excessive_smoothness")
            elif smoothness > 0.75:  # Moderately suspicious
                confidence_score += 0.15
                indicators.append("high_smoothness")

            # 3. Check for lack of sensor noise (real cameras have noise patterns)
            noise_level = np.std(grayscale.astype(float))
            if noise_level < 5.0:  # Very low noise suggests synthetic
                confidence_score += 0.20
                indicators.append("low_noise")
            elif noise_level < 10.0:
                confidence_score += 0.10
                indicators.append("moderate_noise")

            # 4. Check for unnatural color distribution (AI often oversaturates)
            hsv = np.array(resized_image.convert("HSV"))
            saturation = hsv[:, :, 1].astype(float)
            mean_saturation = np.mean(saturation)

            if mean_saturation > 180:  # Highly saturated (0-255 scale)
                confidence_score += 0.20
                indicators.append("high_saturation")

            # 5. Check for perfect symmetry (some AI models create symmetric artifacts)
            img_width = img_array.shape[1]
            left_half = img_array[:, : img_width // 2, :]
            right_half = np.fliplr(img_array[:, img_width // 2 :, :])

            if left_half.shape == right_half.shape:
                min_size = min(left_half.shape[1], right_half.shape[1])
                left_crop = left_half[:, :min_size, :]
                right_crop = right_half[:, :min_size, :]

                symmetry_diff = np.mean(
                    np.abs(left_crop.astype(float) - right_crop.astype(float))
                )
                if symmetry_diff < 5.0:  # Almost perfectly symmetric
                    confidence_score += 0.25
                    indicators.append("unnatural_symmetry")

            # Adjusted threshold - be more aggressive
            if confidence_score > 0.35:
                method = f"Statistical: {', '.join(indicators)}"
                return True, method, min(confidence_score, 0.85)

            return False, None, confidence_score

        except Exception as e:
            logger.debug(f"Statistical analysis failed: {e}")
            return False, None, 0.0

    def _calculate_smoothness(self, grayscale: np.ndarray) -> float:
        """Calculate image smoothness score (optimized)."""
        try:
            # Use fast gradient-based smoothness instead of slow scipy generic_filter
            # This is 100x faster and gives similar results
            grad_y = np.diff(grayscale, axis=0)
            grad_x = np.diff(grayscale, axis=1)
            gradient_magnitude = np.mean(np.abs(grad_y[:-1])) + np.mean(
                np.abs(grad_x[:, :-1])
            )
            smoothness = 1.0 / (1.0 + gradient_magnitude / 50.0)
            return float(smoothness)

        except Exception as e:
            logger.debug(f"Smoothness calculation failed: {e}")
            return 0.5  # Neutral score on error

    def _analyze_noise_patterns(
        self, image: Image.Image
    ) -> Tuple[bool, Optional[str], float]:
        """
        Analyze noise patterns for GAN fingerprints (optimized).

        GANs and diffusion models leave specific noise signatures.
        Works on a resized copy to ensure fast processing without losing metadata.

        Returns:
            Tuple of (is_ai, method, confidence)
        """
        try:
            # Create a resized copy for fast processing (preserves original image with metadata)
            width, height = image.size
            max_dim = 512
            if width > max_dim or height > max_dim:
                scale = min(max_dim / width, max_dim / height)
                new_width = int(width * scale)
                new_height = int(height * scale)
                resized_image = image.resize(
                    (new_width, new_height), Image.Resampling.LANCZOS
                )
            else:
                resized_image = image

            # Extract high-frequency noise component
            grayscale = np.array(resized_image.convert("L")).astype(float)

            # Use simple approximation instead of scipy gaussian_filter for speed
            # This is 10x faster and sufficient for noise detection
            from scipy import ndimage

            lowpass = ndimage.gaussian_filter(grayscale, sigma=2)
            noise = grayscale - lowpass

            # Analyze noise characteristics
            noise_std = np.std(noise)
            noise_mean = np.mean(np.abs(noise))

            # Check for periodic patterns in noise (GAN artifact)
            noise_fft = np.fft.fft2(noise)
            noise_magnitude = np.abs(noise_fft)

            # Look for unexpected peaks in noise spectrum
            height, width = noise_magnitude.shape
            center_y, center_x = height // 2, width // 2

            # Sample around center (excluding DC component)
            sample_region = noise_magnitude[
                center_y - 10 : center_y + 10, center_x - 10 : center_x + 10
            ]
            sample_region[10, 10] = 0  # Remove DC component

            if np.max(sample_region) > np.mean(noise_magnitude) * 5:
                # Unusual peak suggests GAN fingerprint
                return True, "Noise pattern: GAN fingerprint", 0.72

            # Check for unnatural noise distribution
            if noise_std < 2.0 and noise_mean < 1.0:
                # Too little noise for a real photograph
                return True, "Noise pattern: Synthetic low noise", 0.65

            return False, None, 0.0

        except ImportError:
            logger.debug("scipy not available for advanced noise analysis")
            return False, None, 0.0
        except Exception as e:
            logger.debug(f"Noise analysis failed: {e}")
            return False, None, 0.0

    def get_detection_stats(self) -> Dict[str, Any]:
        """Get statistics about detection capabilities."""
        return {
            "detection_methods": [
                "metadata_analysis",
                "statistical_analysis",
                "noise_pattern_analysis",
            ],
            "ai_platforms_tracked": len(self.ai_platforms),
            "requires_scipy": True,  # For advanced analysis
        }
